import { useEffect, useState } from 'react';
import { ArrowUpRight, Braces, Boxes, FolderOpen, Globe2, Loader2, RefreshCw, Server } from 'lucide-react';
import { api } from '../../lib/api';
import type { ProjectContext } from '../../lib/artifacts';
import { useStore } from '../../store';
import { useCreative } from '../../creative-store';
import { ContentIcon } from '../ContentIcon';
import { openFolder } from '../../lib/reveal';

export function ProjectUsage({ provider, projectId, sourceRevision = 0 }: { provider: string; projectId: string; sourceRevision?: number }) {
  const [open, setOpen] = useState(false), [context, setContext] = useState<ProjectContext | null>(null);
  const [loading, setLoading] = useState(false), [error, setError] = useState(''), [refresh, setRefresh] = useState(0);
  useEffect(() => {
    if (!open) return;
    let current = true; setLoading(true); setError('');
    void api.getProjectContext(provider, projectId).then(value => {
      if (current) { if (value.provider !== provider || value.project_id !== projectId) throw new Error('Project relationships do not match the selected project.'); setContext(value); }
    }).catch(e => { if (current) setError(String(e)); }).finally(() => { if (current) setLoading(false); });
    return () => { current = false; };
  }, [open, provider, projectId, refresh, sourceRevision]);
  const targets = context?.provider === provider && context.project_id === projectId ? context.targets : [];
  const button = 'inline-flex items-center gap-1.5 rounded-md px-2 py-1.5 text-xs text-brand transition-colors hover:bg-brand/10';
  function openConfig(target: ProjectContext['targets'][number], path: string) {
    if (target.kind === 'server') {
      useCreative.setState({ serverFileTarget: { serverId: target.id, path } });
      useStore.getState().openServer(target.id);
      return;
    }
    useCreative.setState({ workbenchTarget: { instanceId: target.id, path, mode: 'config' } });
    useStore.getState().setView('config');
  }
  return <details className="mx-6 mb-5 rounded-xl border border-border-soft bg-surface/80" onToggle={event => setOpen(event.currentTarget.open)}>
    <summary className="flex cursor-pointer items-center gap-2 px-4 py-3 text-sm font-medium text-content"><Boxes className="size-4 text-brand" />Used in your library<span className="ml-auto text-xs font-normal text-content-faint">Instances · settings · dependencies</span></summary>
    {open && <div className="space-y-3 border-t border-border-soft p-4">
      <div className="flex items-center justify-between gap-3"><p className="text-xs text-content-muted">Installed copies and settings, connected by project identity.</p><button type="button" className={button} disabled={loading} aria-label="Refresh project relationships" onClick={() => setRefresh(n=>n+1)}>{loading ? <Loader2 size={14} className="animate-spin" /> : <RefreshCw size={14} />}Refresh</button></div>
      {error && <p role="alert" className="text-xs text-red-300">{error}</p>}
      {loading && !targets.length && <p role="status" className="text-xs text-content-faint">Finding installed copies and settings…</p>}
      {!loading && !error && !targets.length && <p className="text-xs text-content-faint">No indexed copies of this project in your instances or servers.</p>}
      {targets.map(target => <section key={`${target.kind}:${target.id}`} aria-label={`Used in ${target.name}`} className="rounded-xl border border-border-soft bg-surface-2/50 p-3">
        <div className="flex items-center gap-3"><ContentIcon src={target.files.find(f=>f.icon_url)?.icon_url} title={target.name} className="size-10 shrink-0 rounded-lg" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-content">{target.name}</p><p className="text-xs text-content-faint">Minecraft {target.minecraft} · {target.loader || 'Vanilla'} · {target.kind}</p></div><button type="button" className={button} onClick={() => target.kind === 'instance' ? useStore.getState().openInstance(target.id) : useStore.getState().openServer(target.id)}>{target.kind === 'server' ? <Server size={13} /> : null}Open {target.kind}<ArrowUpRight size={13} /></button></div>
        <div className="mt-3 space-y-1">{target.files.map(file => <p key={file.file_name} className="flex flex-wrap gap-x-2 text-xs text-content-muted"><span className="font-mono">{file.file_name}</span><span className={file.exists ? 'text-content-faint' : 'text-amber-300'}>{file.exists ? file.enabled ? 'Enabled' : 'Disabled' : 'Missing from disk'} · {file.mod_version || file.version_id || 'Version unknown'}</span></p>)}</div>
        {!!target.configs.length && <div className="mt-3 border-t border-border-soft pt-3"><p className="mb-1 text-[10px] font-semibold uppercase tracking-wider text-content-faint">Settings · {target.configs.length}</p>{target.configs.map(config => <button key={config.path} type="button" className={`flex w-full items-center gap-2 rounded-lg px-2 py-2 text-left text-xs transition-colors hover:bg-brand/10 ${config.exists ? 'text-content-muted' : 'text-amber-300'}`} title={`${config.owner.reason}${config.world ? ' World server settings; this does not establish saved mod content.' : ''}`} onClick={() => openConfig(target,config.path)}><Braces size={14} className="shrink-0 text-brand" /><span className="min-w-0 flex-1 truncate">{config.path}</span>{config.world && <span className="shrink-0 text-content-faint">World settings</span>}{!config.exists && <span>Missing</span>}<ArrowUpRight size={12} /></button>)}</div>}
        {!!target.bundled_mods?.length && <details className="mt-3 border-t border-border-soft pt-3"><summary className="flex cursor-pointer items-center gap-2 text-xs text-content-muted"><Boxes size={14}/>Bundled mods · {target.bundled_mods.length}</summary><p className="my-2 text-[11px] text-content-faint">Included inside these JARs. The game loader decides which candidates to activate; these are not separate installations.</p><div className="grid gap-2 sm:grid-cols-2">{target.bundled_mods.map(mod=><div key={`${mod.file_name}:${mod.archive_path}:${mod.mod_id}`} className="min-w-0 rounded-lg border border-border-soft bg-surface p-3"><p className="text-xs font-medium text-content">{mod.title || mod.mod_id}<span className="ml-2 font-normal text-content-faint">{mod.mod_version || 'Version unknown'}</span></p><p className="mt-1 text-[11px] text-content-faint">{mod.mod_id} · {mod.enabled ? 'Container enabled' : 'Container disabled'}</p><p className="mt-2 break-all font-mono text-[10px] text-content-muted">{mod.file_name} → {mod.archive_path}</p><details className="mt-2 text-[10px] text-content-faint"><summary className="cursor-pointer">File fingerprint</summary><p className="mt-1 break-all font-mono" title="Measured SHA-256 of the embedded JAR">SHA-256 · {mod.sha256}</p></details></div>)}</div></details>}
        {!!target.dependencies.length && <details className="mt-3 border-t border-border-soft pt-3"><summary className="cursor-pointer text-xs text-content-muted">Dependencies & dependents · {target.dependencies.length}</summary><p className="my-2 text-[11px] text-content-faint">Declared by installed mod manifests. Version ranges and sides are shown as declared; runtime compatibility is not yet verified.</p><div className="space-y-2">{target.dependencies.map((dependency,index) => <div key={`${dependency.file_name}:${dependency.mod_id}:${index}`} className="rounded-lg bg-surface p-2.5 text-xs"><p className="font-medium text-content">{dependency.direction === 'dependency' ? `${dependency.owner} → ${dependency.mod_id}` : `${dependency.source_title || dependency.owner} → this mod`}<span className="ml-2 text-content-faint">{dependency.kind}{dependency.alternative_group && ' · one of alternatives'}{dependency.unless != null && ' · conditional'}{!dependency.source_enabled && ' · source disabled'}</span></p><p className="mt-1 text-content-faint">{Array.isArray(dependency.version_range) ? dependency.version_range.join(' or ') : typeof dependency.version_range === 'object' ? JSON.stringify(dependency.version_range) : dependency.version_range || 'Range not declared'} · {dependency.side}</p><p className="mt-1 break-all text-[11px] text-content-faint">{dependency.unless != null && `Unless: ${JSON.stringify(dependency.unless)} · `}{dependency.qualified_id && dependency.qualified_id !== dependency.mod_id && `${dependency.qualified_id} · `}{dependency.file_name} · {dependency.archive_path}{dependency.manifest}</p>{!!dependency.installed_targets.length && <div className="mt-2 space-y-1 border-t border-border-soft pt-2">{dependency.installed_targets.map((copy,copyIndex)=><p key={copyIndex} className="break-all text-[11px] text-content-muted"><span className="text-brand">{copy.bundled ? 'Bundled in' : 'Installed in'}</span> {copy.file_name} · {copy.mod_version || 'Version unknown'}{!copy.enabled && ' · disabled'}{copy.archive_path && <span className="block font-mono text-[10px] text-content-faint">{copy.archive_path}</span>}</p>)}</div>}</div>)}</div></details>}
        {!!target.worlds?.length && <details className="mt-3 border-t border-border-soft pt-3"><summary className="flex cursor-pointer items-center gap-2 text-xs text-content-muted"><Globe2 size={14}/>World connections · {target.worlds.length}</summary><p className="my-2 text-[11px] text-content-faint">Observed pack selections and dimension storage. These records do not establish safe mod removal or runtime compatibility.</p><div className="space-y-2">{target.worlds.map(world=><section key={world.folder} aria-label={`World connection ${world.name}`} className="rounded-lg bg-surface p-3"><div className="flex items-center justify-between gap-2"><span className="text-xs font-medium text-content">{world.name}{world.minecraft&&<span className="ml-2 text-content-faint">{world.minecraft}</span>}</span><button type="button" className={button} onClick={()=>void openFolder(world.directory)}><FolderOpen size={13}/>Open world folder</button></div>{world.evidence.map((e,index)=><p key={index} title={e.detail} className="mt-2 break-all text-xs text-content-muted"><span className="text-brand">{e.kind==='dimension_storage'?'Dimension storage':e.kind==='enabled_datapack'?'Enabled data pack':'Disabled data pack'}</span> · {e.mod_id}<span className="mt-0.5 block font-mono text-[10px] text-content-faint">{e.path}</span></p>)}{world.warning&&<p className="mt-2 text-xs text-amber-300">{world.warning}</p>}</section>)}</div></details>}
        {target.warnings.map(warning=><p key={warning} className="mt-2 text-xs text-amber-300">{warning}</p>)}
      </section>)}
      {context?.warnings.map((warning,index)=><p key={index} className="text-xs text-amber-300">{warning.message}</p>)}
    </div>}
  </details>;
}
