'use strict';
const $=id=>document.getElementById(id);
let toastTimer=null;
const cmd=(name,payload={})=>window.companion.command(name,payload);
function toast(message){const el=$('toast');el.textContent=String(message||'');el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
async function action(name,payload={},success=''){try{const result=await cmd(name,payload);if(success)toast(success);return result}catch(err){toast(err?.message||String(err));throw err}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function formatWhen(value){if(!value)return 'Not checked yet';const d=new Date(value);return Number.isNaN(d.valueOf())?String(value):d.toLocaleString()}
function renderSourceCenter(center){
  const catalog=(center?.catalogs||[]).find(c=>c.id===center.activeCatalogId)||center?.catalogs?.[0];
  if(!catalog){$('sourceBody').innerHTML='<div class="empty-utility">No catalog is loaded.</div>';return}
  const sources=catalog.sources||[],problems=sources.filter(s=>s.status==='error'||s.status==='sign-in-required').length,statusClass=problems?'attention':catalog.sync?.state==='watching'?'watching':'';
  const cards=sources.length?sources.map(src=>{const open=src.url?`<button data-source-action="open" data-source-id="${esc(src.id)}" data-url="${esc(src.url)}">Open here ↗</button>`:'';const signin=src.status==='sign-in-required'?`<button data-source-action="signin" data-source-id="${esc(src.id)}">Sign into Google</button>`:'';const endpoint=src.location==='local'?(src.path||'Local file'):(src.url||src.exportUrl||'Google source');return `<article class="source-card ${esc(src.status||'pending')}"><div class="source-card-head"><div><strong>${esc(src.label||'Source')}</strong><span>${esc(src.location||'source')} · ${esc(src.role||'auto')} · ${esc((src.format||'').toUpperCase())}</span></div><b class="source-state">${esc(src.status||'pending')}</b></div><code>${esc(endpoint)}</code><small>Last checked: ${esc(formatWhen(src.lastChecked))}</small>${src.error?`<p class="source-error">${esc(src.error)}</p>`:''}<div class="source-card-actions"><label class="source-toggle"><input type="checkbox" data-source-toggle="${esc(src.id)}" ${src.autoRefresh!==false?'checked':''}> Auto refresh</label>${signin}<button data-source-action="refresh" data-source-id="${esc(src.id)}">Refresh</button>${open}<button class="danger-link" data-source-action="remove" data-source-id="${esc(src.id)}">Remove</button></div></article>`}).join(''):'<div class="empty-utility">This catalog is an offline snapshot with no tracked sources yet. Import local files or add a Google source above.</div>';
  $('sourceBody').innerHTML=`<div class="source-health ${statusClass}"><span class="health-ring">${problems?'!':catalog.sync?.state==='watching'?'↻':'✓'}</span><div><strong>${esc(catalog.name)} · ${catalog.entries} entries</strong><p>${esc(catalog.sync?.label||'Snapshot ready')}. ${sources.length} tracked source${sources.length===1?'':'s'}; ${catalog.assets||0} projects with live source media. Changes are hash-compared before the catalog is regenerated.</p></div></div><div class="source-grid"><div><span>Active catalog</span><strong>${esc(catalog.name)}</strong><small>${catalog.collections||0} collections · ${catalog.entries||0} entries</small></div><div><span>Refresh behavior</span><strong>Local ~1.6s · Google ~2 min</strong><small>Google checks shortly after launch and reuses the authenticated in-app cookie jar without Electron fetch.</small></div></div><div class="source-list">${cards}</div><p class="source-note"><b>Authority rule:</b> Sheet/XLSX/CSV/JSON sources own sortable rows. Docs and PDFs are narrative/fixed reference layers, so an older PDF cannot silently overwrite a newer master Sheet.</p>`;
}
async function refresh(){renderSourceCenter(await cmd('catalog-list'))}
$('sourceClose').onclick=()=>cmd('source-center-close').catch(()=>window.close());
$('importLocal').onclick=async()=>{try{await action('catalog-import-dialog',{mode:$('importMode').value},'Local sources ingested');await refresh()}catch{}};
$('refreshSources').onclick=async()=>{const b=$('refreshSources');b.disabled=true;try{await action('catalog-refresh',{},'Active sources checked');await refresh()}finally{b.disabled=false}};
$('refreshAllCatalogs').onclick=async()=>{const b=$('refreshAllCatalogs');b.disabled=true;try{await action('catalog-refresh-all',{},'All catalog sources checked');await refresh()}finally{b.disabled=false}};
$('revealCatalogData').onclick=()=>cmd('catalog-reveal').catch(err=>toast(err?.message||String(err)));
$('addGoogle').onclick=async()=>{const url=$('googleUrl').value.trim();if(!url){toast('Paste a Google source URL first');return}const b=$('addGoogle');b.disabled=true;try{await action('catalog-add-google',{url,role:$('googleRole').value||undefined,mode:$('googleMode').value,name:$('googleCatalogName').value.trim()||undefined},'Google source tracked');$('googleUrl').value='';$('googleCatalogName').value='';await refresh()}catch{}finally{b.disabled=false}};
$('sourceBody').onclick=async e=>{const b=e.target.closest('[data-source-action]');if(!b)return;const sourceId=b.dataset.sourceId,act=b.dataset.sourceAction;try{if(act==='open'){await cmd('new-tab',{url:b.dataset.url});await cmd('source-center-close')}else if(act==='signin'){await cmd('catalog-google-signin');await cmd('source-center-close')}else if(act==='refresh'){await action('catalog-source-refresh',{sourceId},'Source checked');await refresh()}else if(act==='remove'){if(confirm('Remove this source definition from the active catalog? The source file itself will not be deleted.')){await action('catalog-remove-source',{sourceId},'Source removed');await refresh()}}}catch{}};
$('sourceBody').onchange=async e=>{const input=e.target.closest('[data-source-toggle]');if(!input)return;try{await action('catalog-toggle-source',{sourceId:input.dataset.sourceToggle,enabled:input.checked},input.checked?'Auto refresh enabled':'Auto refresh paused');await refresh()}catch{input.checked=!input.checked}};
window.companion.onState(()=>refresh().catch(()=>{}));
refresh().catch(err=>toast(err?.message||String(err)));
