'use strict';
const $=id=>document.getElementById(id);
let state=null;
function cmd(name,payload={}){return window.companion.command(name,payload)}
function activeCatalog(){return state?.catalog||{name:'Catalog',entries:0,assets:0,sync:{state:'snapshot',label:'Offline snapshot'}}}
function safeHost(url){try{return new URL(url).hostname}catch{return ''}}
function render(next){state=next||state||{};const a=state.active||{id:'catalog'},c=activeCatalog(),catalog=a.id==='catalog';const collapsed=!!state.statusBarCollapsed;document.body.classList.toggle('collapsed',collapsed);$('statusToggle').title='Collapse status bar · Ctrl+Shift+B';$('statusToggle').setAttribute('aria-label','Collapse status bar');$('statusReveal').title='Expand status bar · Ctrl+Shift+B';$('statusText').textContent=catalog?`${c.name||'Catalog'} · ${c.sync?.label||'snapshot ready'}`:(a.loading?`Loading ${safeHost(a.url)}…`:`${safeHost(a.url)} · ready`);$('statusDot').className='status-dot '+(c.sync?.state==='error'?'attention':c.sync?.state==='watching'?'watching':'');const ab=state.adblock||{};const blocked=Number(ab.blocked)||0;$('adblockStatus').textContent=ab.filteringVerified?`uBO ${ab.version||''} · verified${blocked?` · ${blocked} blocked`:''}`:ab.loaded?`uBO ${ab.version||''} · loaded / not filtering`:ab.enabled===false?'uBO · off':'uBO · warning';$('adblockStatus').title=ab.message||'uBlock Origin';const pct=Math.round((state.splitRatio||.46)*100);$('splitStatus').textContent=state.splitMode?`${state.splitSide==='web-left'?'Site':'Catalog'} ${pct}% · ${state.splitSide==='web-left'?'Catalog':'Site'} ${100-pct}%`:'Full view';$('runtimeStatus').textContent=state.runtime||'Chromium';$('catalogStatus').textContent=`${c.entries||0} entries · ${c.assets||0} live-media projects · ${c.sync?.label||'snapshot'}`}
$('statusToggle').addEventListener('click',()=>cmd('statusbar-toggle',{collapsed:true}).catch(()=>{}));
$('statusReveal').addEventListener('click',()=>cmd('statusbar-toggle',{collapsed:false}).catch(()=>{}));
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='b'){e.preventDefault();cmd('statusbar-toggle').catch(()=>{})}});
window.companion.onState(render);window.companion.onStatus(s=>{if(!document.body.classList.contains('collapsed'))$('statusText').textContent=s});cmd('get-state').then(render).catch(()=>{});
