(()=>{'use strict';
const VAULT=window.ENDERLOOM_CREATOR_VAULT||{};
const creators=Array.isArray(VAULT.creators)?VAULT.creators:[];
const videos=Array.isArray(VAULT.videos)?VAULT.videos:[];
const setupPacks=Array.isArray(VAULT.channelSetupPacks)?VAULT.channelSetupPacks:[];
if(!creators.length&&!videos.length)return;
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>\"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[ch]));
const norm=value=>String(value??'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'');
const creatorById=new Map(creators.map(c=>[c.id,c]));
const storageKey='enderloom:creator-vault:pinned:v1';
let pinned=new Set();
try{pinned=new Set(JSON.parse(localStorage.getItem(storageKey)||'[]'))}catch{}
const state={view:'recommendations',platform:'all',creator:'all',query:''};
function persistPins(){try{localStorage.setItem(storageKey,JSON.stringify([...pinned]))}catch{}}
function creatorInitials(c){return String(c.title||c.handle||'?').split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'?'}
function platformLabel(p){return p==='youtube'?'YouTube':p==='tiktok'?'TikTok':p||'Creator'}
function coverageLabel(c){const cov=c.coverage||{};if(cov.complete)return'Complete';if(cov.state==='in-progress')return'Indexing';if(cov.state==='legacy-partial')return'Legacy partial';if(cov.state==='live-gate-pending')return'Live gate';if(cov.state==='link-refresh-pending')return'Link refresh';return'Queued'}
function coverageCount(c){const cov=c.coverage||{};if(Number.isFinite(Number(cov.recommendationCount)))return`${Number(cov.recommendationCount)} recs`;if(Number.isFinite(Number(cov.indexedVideos)))return`${Number(cov.indexedVideos)} videos`;if(Number.isFinite(Number(cov.expectedVideos)))return`${Number(cov.expectedVideos)} expected`;return coverageLabel(c)}
function sourceCreator(c){return `<a class="cv-source-link" href="${esc(c.url)}" target="_blank" rel="noreferrer">Open ${esc(platformLabel(c.platform))}</a>`}
function creatorCard(c){const isPinned=pinned.has(c.id),selected=state.creator===c.id;return `<article class="cv-creator-card${selected?' selected':''}" data-creator-id="${esc(c.id)}"><div class="cv-avatar ${esc(c.platform)}">${esc(creatorInitials(c))}</div><div class="cv-creator-main"><div class="cv-creator-title"><strong>${esc(c.title)}</strong><span class="cv-platform ${esc(c.platform)}">${esc(platformLabel(c.platform))}</span></div><div class="cv-handle">${esc(c.handle)}</div><div class="cv-mini-row"><span>${esc(c.role)}</span><span>${esc(coverageCount(c))}</span>${c.required?'<span>core</span>':''}</div></div><div class="cv-creator-actions"><button type="button" class="cv-icon-button" data-pin-creator="${esc(c.id)}" aria-label="${isPinned?'Unpin':'Pin'} ${esc(c.title)}" title="${isPinned?'Unpin creator':'Pin creator'}">${isPinned?'Pinned':'Pin'}</button>${sourceCreator(c)}</div></article>`}
function modSearchButton(mod){if(mod.url)return `<a class="cv-action primary" href="${esc(mod.url)}" target="_blank" rel="noreferrer">Project</a>`;return `<button type="button" class="cv-action" data-catalog-search="${esc(mod.name)}">Find in Enderloom</button>`}
function modCard(mod,video){const creator=creatorById.get(video.creatorId)||{};const loaders=(mod.loader||[]).map(x=>`<span class="cv-loader">${esc(x)}</span>`).join('');return `<article class="cv-mod-card"><div class="cv-mod-head"><div><h4>${esc(mod.name)}</h4><div class="cv-mod-meta">${loaders}<span class="cv-confidence">source-backed</span></div></div><a class="cv-time" href="${esc(mod.videoLink||video.url)}" target="_blank" rel="noreferrer">${esc(mod.timestamp||'Video')}</a></div><p>${esc(mod.evidence||'Creator source evidence recorded.')}</p><div class="cv-mod-foot"><span>Recommended by ${esc(creator.title||creator.handle||video.creatorId)}</span><div>${modSearchButton(mod)}<a class="cv-action" href="${esc(mod.videoLink||video.url)}" target="_blank" rel="noreferrer">Watch moment</a></div></div></article>`}
function videoCard(video){const creator=creatorById.get(video.creatorId)||{};const mods=video.mods||[];return `<section class="cv-video-card"><header><div><div class="cv-eyebrow">${esc(creator.title||creator.handle||video.creatorId)} / ${esc(video.publishedAt||'date unknown')}</div><h3>${esc(video.title)}</h3><div class="cv-video-meta"><span>${mods.length} recommendations</span><span>${esc((video.evidenceKinds||[]).join(' + ')||'source evidence')}</span></div></div><div class="cv-video-actions"><button type="button" class="cv-action" data-copy-video="${esc(video.id)}">Copy mod names</button><a class="cv-action primary" href="${esc(video.url)}" target="_blank" rel="noreferrer">Open video</a></div></header><div class="cv-mod-grid">${mods.map(mod=>modCard(mod,video)).join('')}</div></section>`}
function creatorMatches(c){if(state.platform!=='all'&&c.platform!==state.platform)return false;if(state.creator!=='all'&&c.id!==state.creator)return false;if(state.query&&!norm([c.title,c.handle,c.role,c.status,c.coverage?.state,c.coverage?.notes].join(' ')).includes(norm(state.query)))return false;return true}
function videoMatches(v){const creator=creatorById.get(v.creatorId)||{};if(state.platform!=='all'&&creator.platform!==state.platform)return false;if(state.creator!=='all'&&v.creatorId!==state.creator)return false;if(!state.query)return true;const q=norm(state.query);return norm([v.title,creator.title,creator.handle,...(v.mods||[]).flatMap(m=>[m.name,(m.loader||[]).join(' '),m.evidence])].join(' ')).includes(q)}
function filteredCreators(){return creators.filter(creatorMatches).sort((a,b)=>Number(pinned.has(b.id))-Number(pinned.has(a.id))||Number(b.required)-Number(a.required)||String(a.title).localeCompare(String(b.title)))}
function filteredVideos(){return videos.filter(videoMatches).sort((a,b)=>String(b.publishedAt).localeCompare(String(a.publishedAt)))}
function renderRecommendations(){const rows=filteredVideos();return rows.length?rows.map(videoCard).join(''):`<div class="cv-empty"><strong>No sourced recommendations match.</strong><span>Broaden the creator or search filter. Nothing was deleted.</span></div>`}
function renderCreators(){const rows=filteredCreators();return rows.length?`<div class="cv-creator-grid">${rows.map(creatorCard).join('')}</div>`:`<div class="cv-empty"><strong>No creators match.</strong><span>Reset the filters to return to the full creator ledger.</span></div>`}
function renderSetup(){const rows=setupPacks.filter(p=>state.creator==='all'||p.creatorId===state.creator).filter(p=>!state.query||norm([p.name,p.evidence].join(' ')).includes(norm(state.query)));return rows.length?`<div class="cv-setup-grid">${rows.map(p=>{const c=creatorById.get(p.creatorId)||{};return `<article class="cv-setup-card"><div class="cv-eyebrow">Used across ${p.sourceVideoIds?.length||0} indexed videos</div><h3>${esc(p.name)}</h3><p>${esc(p.evidence)}</p><div class="cv-mini-row"><span>${esc(c.title||p.creatorId)}</span><span>${esc(p.projectType||'resourcepack')}</span></div><button type="button" class="cv-action" data-catalog-search="${esc(p.name)}">Find in Enderloom</button></article>`}).join('')}</div>`:`<div class="cv-empty"><strong>No recurring setup packs match.</strong><span>These are separated from the creator's main video recommendations.</span></div>`}
function renderBody(){const body=$('creatorVaultBody');if(!body)return;body.innerHTML=state.view==='creators'?renderCreators():state.view==='setup'?renderSetup():renderRecommendations();document.querySelectorAll('[data-cv-view]').forEach(b=>b.classList.toggle('active',b.dataset.cvView===state.view));document.querySelectorAll('[data-cv-platform]').forEach(b=>b.classList.toggle('active',b.dataset.cvPlatform===state.platform));const creatorSelect=$('creatorVaultCreatorFilter');if(creatorSelect)creatorSelect.value=state.creator;const result=$('creatorVaultResultLabel');if(result){const count=state.view==='creators'?filteredCreators().length:state.view==='setup'?setupPacks.filter(p=>state.creator==='all'||p.creatorId===state.creator).filter(p=>!state.query||norm([p.name,p.evidence].join(' ')).includes(norm(state.query))).length:filteredVideos().reduce((n,v)=>n+(v.mods||[]).length,0);result.textContent=`${count} ${state.view==='recommendations'?'recommendations':state.view==='creators'?'creators':'setup packs'}`}}
function closeVault(){const modal=$('creatorVaultModal'),backdrop=$('creatorVaultBackdrop');if(modal)modal.hidden=true;if(backdrop)backdrop.hidden=true;document.body.classList.remove('creator-vault-open')}
function openVault(){const modal=$('creatorVaultModal'),backdrop=$('creatorVaultBackdrop');if(!modal||!backdrop)return;modal.hidden=false;backdrop.hidden=false;document.body.classList.add('creator-vault-open');renderBody();setTimeout(()=>$('creatorVaultSearch')?.focus(),0)}
function searchCatalog(term){closeVault();const input=$('searchInput');if(!input)return;input.value=term;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus()}
function copyText(text){if(navigator.clipboard?.writeText)return navigator.clipboard.writeText(text).catch(()=>fallbackCopy(text));fallbackCopy(text);return Promise.resolve()}
function fallbackCopy(text){const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();try{document.execCommand('copy')}catch{}area.remove()}
function buildShell(){const quick=document.querySelector('.quick-filters');if(quick&&!$('creatorVaultButton')){const button=document.createElement('button');button.id='creatorVaultButton';button.type='button';button.className='quick-chip creator-vault-chip';button.innerHTML=`Creators <span>${VAULT.stats?.recommendations||0}</span>`;button.addEventListener('click',openVault);quick.appendChild(button)}
const creatorOptions=creators.slice().sort((a,b)=>String(a.title).localeCompare(String(b.title))).map(c=>`<option value="${esc(c.id)}">${esc(c.title)} (${esc(platformLabel(c.platform))})</option>`).join('');const root=document.createElement('div');root.id='creator-vault-root';root.innerHTML=`<div id="creatorVaultBackdrop" class="cv-backdrop" hidden></div><section id="creatorVaultModal" class="creator-vault-modal" role="dialog" aria-modal="true" aria-labelledby="creatorVaultTitle" hidden><header class="cv-hero"><div><div class="cv-eyebrow">Enderloom creator intelligence</div><h2 id="creatorVaultTitle">Creator Vault</h2><p>Browse every tracked creator and jump straight to the exact moment they recommended a mod. Source evidence stays attached; unresolved project links stay unresolved.</p></div><button type="button" class="cv-close" data-cv-close aria-label="Close Creator Vault">Close</button></header><section class="cv-stats"><div><span>Tracked creators</span><strong>${Number(VAULT.stats?.creators||creators.length)}</strong></div><div><span>Indexed videos</span><strong>${Number(VAULT.stats?.videos||videos.length)}</strong></div><div><span>Sourced recommendations</span><strong>${Number(VAULT.stats?.recommendations||0)}</strong></div><div><span>Recurring setup packs</span><strong>${Number(VAULT.stats?.setupPacks||setupPacks.length)}</strong></div></section><div class="cv-toolbar"><div class="cv-tabs"><button type="button" class="active" data-cv-view="recommendations">Recommendations</button><button type="button" data-cv-view="creators">Creators</button><button type="button" data-cv-view="setup">Setup packs</button></div><div class="cv-platform-tabs"><button type="button" class="active" data-cv-platform="all">All</button><button type="button" data-cv-platform="youtube">YouTube</button><button type="button" data-cv-platform="tiktok">TikTok</button></div><div class="cv-search-row"><input id="creatorVaultSearch" type="search" autocomplete="off" placeholder="Search creators, mods, loaders, evidence..."><select id="creatorVaultCreatorFilter"><option value="all">All creators</option>${creatorOptions}</select><span id="creatorVaultResultLabel"></span></div></div><div id="creatorVaultBody" class="cv-body"></div><footer class="cv-footer"><span>Strategy: ${esc(VAULT.strategy||'full-history-first/incremental-after')}</span><span>${VAULT.diagnostics?.length?`${VAULT.diagnostics.length} loader note(s)`:'Creator data loaded cleanly'}</span></footer></section>`;document.body.appendChild(root);
$('creatorVaultBackdrop').addEventListener('click',closeVault);root.addEventListener('click',event=>{const close=event.target.closest('[data-cv-close]');if(close){closeVault();return}const view=event.target.closest('[data-cv-view]');if(view){state.view=view.dataset.cvView;renderBody();return}const platform=event.target.closest('[data-cv-platform]');if(platform){state.platform=platform.dataset.cvPlatform;renderBody();return}const pin=event.target.closest('[data-pin-creator]');if(pin){const id=pin.dataset.pinCreator;pinned.has(id)?pinned.delete(id):pinned.add(id);persistPins();renderBody();return}const creatorCardEl=event.target.closest('[data-creator-id]');if(creatorCardEl&&!event.target.closest('a,button')){state.creator=creatorCardEl.dataset.creatorId;state.view='recommendations';renderBody();return}const search=event.target.closest('[data-catalog-search]');if(search){searchCatalog(search.dataset.catalogSearch);return}const copy=event.target.closest('[data-copy-video]');if(copy){const video=videos.find(v=>v.id===copy.dataset.copyVideo);if(video){copyText((video.mods||[]).map(m=>m.name).join('\n'));copy.textContent='Copied';setTimeout(()=>copy.textContent='Copy mod names',1200)}}});$('creatorVaultSearch').addEventListener('input',event=>{state.query=event.target.value||'';renderBody()});$('creatorVaultCreatorFilter').addEventListener('change',event=>{state.creator=event.target.value||'all';renderBody()});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('creatorVaultModal')?.hidden)closeVault()});renderBody()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',buildShell,{once:true});else buildShell();
})();
