(()=>{'use strict';
const VAULT=window.ENDERLOOM_CREATOR_VAULT||{};
const creators=Array.isArray(VAULT.creators)?VAULT.creators:[];
const videos=Array.isArray(VAULT.videos)?VAULT.videos:[];
const projects=Array.isArray(VAULT.projects)?VAULT.projects:[];
const setupPacks=Array.isArray(VAULT.channelSetupPacks)?VAULT.channelSetupPacks:[];
if(!creators.length&&!videos.length)return;
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>\"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[ch]));
const norm=value=>String(value??'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'');
const creatorById=new Map(creators.map(c=>[c.id,c]));
const videoById=new Map(videos.map(v=>[v.id,v]));
const storageKey='enderloom:creator-vault:pinned:v1';
let pinned=new Set();
try{pinned=new Set(JSON.parse(localStorage.getItem(storageKey)||'[]'))}catch{}
const state={view:'recommendations',platform:'all',creator:'all',query:''};
function persistPins(){try{localStorage.setItem(storageKey,JSON.stringify([...pinned]))}catch{}}
function creatorInitials(c){return String(c.title||c.handle||'?').split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'?'}
function platformLabel(p){return p==='youtube'?'YouTube':p==='tiktok'?'TikTok':p||'Creator'}
function coverageLabel(c){const cov=c.coverage||{};if(cov.complete)return'Complete';if(cov.state==='in-progress')return'Indexing';if(cov.state==='legacy-partial')return'Legacy partial';if(cov.state==='live-gate-pending')return'Live gate';if(cov.state==='link-refresh-pending')return'Link refresh';return'Queued'}
function coverageCount(c){const cov=c.coverage||{};if(Number.isFinite(Number(cov.recommendationCount)))return`${Number(cov.recommendationCount)} recs`;if(Number.isFinite(Number(cov.indexedVideos)))return`${Number(cov.indexedVideos)} videos`;if(Number.isFinite(Number(cov.expectedVideos)))return`${Number(cov.expectedVideos)} expected`;return coverageLabel(c)}
function sourceCreator(c){return `<a class="cv-source-link" href="${esc(c.url)}" target="_blank" rel="noreferrer">Open ${esc(platformLabel(c.platform))}</a>`}
function creatorCard(c){const isPinned=pinned.has(c.id),selected=state.creator===c.id;return `<article class="cv-creator-card${selected?' selected':''}" data-creator-id="${esc(c.id)}"><div class="cv-avatar ${esc(c.platform)}">${esc(creatorInitials(c))}</div><div class="cv-creator-main"><div class="cv-creator-title"><strong>${esc(c.title)}</strong><span class="cv-platform ${esc(c.platform)}">${esc(platformLabel(c.platform))}</span></div><div class="cv-handle">${esc(c.handle)}</div><div class="cv-mini-row"><span>${esc(c.role)}</span><span>${esc(coverageCount(c))}</span>${c.required?'<span>core</span>':''}</div></div><div class="cv-creator-actions"><button type="button" class="cv-icon-button" data-pin-creator="${esc(c.id)}" aria-label="${isPinned?'Unpin':'Pin'} ${esc(c.title)}" title="${isPinned?'Unpin creator':'Pin creator'}">${isPinned?'Pinned':'Pin'}</button>${sourceCreator(c)}</div></article>`}
function providerForUrl(link){if(link?.provider)return String(link.provider);const url=String(link?.url||'');if(/modrinth\.com/i.test(url))return'Modrinth';if(/curseforge\.com/i.test(url))return'CurseForge';if(/github\.com/i.test(url))return'GitHub';return url?'Official':''}
function entityLinks(entity){const links=Array.isArray(entity?.providerLinks)?entity.providerLinks:[];if(links.length)return links;return entity?.url?[{provider:entity.provider||providerForUrl({url:entity.url}),url:entity.url}]:[]}
function projectTypeLabel(type){const value=String(type||'mod').toLowerCase();return value==='resourcepack'?'Resource Pack':value==='datapack'?'Data Pack':value==='modpack'?'Modpack':value==='shader'?'Shader':value==='plugin'?'Plugin':'Mod'}
function providerClass(value){return norm(value).replace(/[^a-z0-9_-]+/g,'-')}
function providerBadges(entity){const seen=new Set();return entityLinks(entity).map(link=>providerForUrl(link)).filter(provider=>provider&&!seen.has(provider)&&seen.add(provider)).map(provider=>`<span class="cv-provider ${esc(providerClass(provider))}" title="Verified direct project home">${esc(provider)}</span>`).join('')}
function providerActions(entity,name){const links=entityLinks(entity);if(!links.length)return `<button type="button" class="cv-action" data-catalog-search="${esc(name)}">Find in Enderloom</button>`;return links.map((link,index)=>{const provider=providerForUrl(link),label=link.label?`${provider} (${link.label})`:provider;return `<a class="cv-action${index===0?' primary':''}" href="${esc(link.url)}" target="_blank" rel="noreferrer" title="Open exact ${esc(label)} project page">${esc(label)}</a>`}).join('')}
function modCard(mod,video){const creator=creatorById.get(video.creatorId)||{};const loaders=(mod.loader||[]).map(x=>`<span class="cv-loader">${esc(x)}</span>`).join('');const providers=providerBadges(mod);const typeBadge=`<span class="cv-project-type ${esc(String(mod.projectType||'mod').toLowerCase())}">${esc(projectTypeLabel(mod.projectType))}</span>`;return `<article class="cv-mod-card${entityLinks(mod).length?' provider-verified':''}"><div class="cv-mod-head"><div><h4>${esc(mod.canonicalName||mod.name)}</h4>${mod.canonicalName&&mod.canonicalName!==mod.name?`<div class="cv-alias-line">Listed here as ${esc(mod.name)}</div>`:''}<div class="cv-mod-meta">${typeBadge}${providers}${loaders}<span class="cv-confidence">source-backed</span></div></div><a class="cv-time" href="${esc(mod.videoLink||video.url)}" target="_blank" rel="noreferrer">${esc(mod.timestamp||'Video')}</a></div><p>${esc(mod.evidence||'Creator source evidence recorded.')}</p><div class="cv-mod-foot"><span>Recommended by ${esc(creator.title||creator.handle||video.creatorId)}</span><div>${providerActions(mod,mod.canonicalName||mod.name)}<a class="cv-action" href="${esc(mod.videoLink||video.url)}" target="_blank" rel="noreferrer">Watch moment</a></div></div></article>`}
function videoCard(video){const creator=creatorById.get(video.creatorId)||{};const mods=video.mods||[],verified=new Set(mods.filter(m=>entityLinks(m).length).map(m=>m.canonicalProjectId||m.name)).size;return `<section class="cv-video-card"><header><div><div class="cv-eyebrow">${esc(creator.title||creator.handle||video.creatorId)} / ${esc(video.publishedAt||'date unknown')}</div><h3>${esc(video.title)}</h3><div class="cv-video-meta"><span>${mods.length} recommendation mentions</span>${verified?`<span>${verified} linked projects</span>`:''}<span>${esc((video.evidenceKinds||[]).join(' + ')||'source evidence')}</span></div></div><div class="cv-video-actions"><button type="button" class="cv-action" data-copy-video="${esc(video.id)}">Copy mod names</button><a class="cv-action primary" href="${esc(video.url)}" target="_blank" rel="noreferrer">Open video</a></div></header><div class="cv-mod-grid">${mods.map(mod=>modCard(mod,video)).join('')}</div></section>`}
function creatorAllowed(creatorId){const creator=creatorById.get(creatorId)||{};if(state.platform!=='all'&&creator.platform!==state.platform)return false;if(state.creator!=='all'&&creatorId!==state.creator)return false;return true}
function scopedMentions(project){return (project.mentions||[]).filter(m=>creatorAllowed(m.creatorId))}
function projectMatches(project){const mentions=scopedMentions(project);if(!mentions.length)return false;const q=norm(state.query);if(!q)return true;const providerText=entityLinks(project).map(link=>`${providerForUrl(link)} ${link.url}`).join(' ');const mentionText=mentions.flatMap(m=>{const creator=creatorById.get(m.creatorId)||{};return [m.name,m.videoTitle,m.publishedAt,m.evidence,(m.loader||[]).join(' '),creator.title,creator.handle]}).join(' ');return norm([project.name,(project.aliases||[]).join(' '),(project.projectTypes||[]).join(' '),providerText,mentionText].join(' ')).includes(q)}
function filteredProjects(){return projects.filter(projectMatches).sort((a,b)=>{const am=scopedMentions(a).length,bm=scopedMentions(b).length;return bm-am||String(a.name).localeCompare(String(b.name))})}
function mentionRow(mention){const creator=creatorById.get(mention.creatorId)||{};const video=videoById.get(mention.videoId)||{};const loader=(mention.loader||[]).length?` · ${(mention.loader||[]).map(esc).join(' / ')}`:'';return `<li><a href="${esc(mention.videoLink||video.url)}" target="_blank" rel="noreferrer"><strong>${esc(creator.title||creator.handle||mention.creatorId)}</strong> · ${esc(mention.timestamp||'Video')}</a><span>${esc(mention.videoTitle||video.title||mention.videoId)}${loader}</span>${mention.name&&mention.name!==(mention.canonicalName||'')?`<small>Source label: ${esc(mention.name)}</small>`:''}</li>`}
function mergedProjectCard(project){const mentions=scopedMentions(project);const aliases=(project.aliases||[]).filter(Boolean);const providerLinks=entityLinks(project);const providerSet=new Set(providerLinks.map(providerForUrl));const creatorCount=new Set(mentions.map(m=>m.creatorId)).size;const videoCount=new Set(mentions.map(m=>m.videoId)).size;const typeBadges=(project.projectTypes||[project.projectType||'mod']).map(type=>`<span class="cv-project-type ${esc(String(type).toLowerCase())}">${esc(projectTypeLabel(type))}</span>`).join('');return `<article class="cv-merged-card${providerLinks.length?' provider-verified':''}"><header><div><div class="cv-eyebrow">Merged canonical project</div><h3>${esc(project.name)}</h3><div class="cv-mod-meta">${typeBadges}${providerBadges(project)}<span class="cv-confidence">${mentions.length} mention${mentions.length===1?'':'s'}</span></div>${aliases.length?`<div class="cv-aliases"><strong>Also listed as:</strong> ${aliases.map(esc).join(' · ')}</div>`:''}</div><div class="cv-provider-actions">${providerActions(project,project.name)}</div></header><div class="cv-merged-summary"><span>${mentions.length} recommendation mention${mentions.length===1?'':'s'}</span><span>${creatorCount} creator${creatorCount===1?'':'s'}</span><span>${videoCount} video${videoCount===1?'':'s'}</span><span>${providerSet.size?`${providerSet.size} verified provider${providerSet.size===1?'':'s'}`:'provider link pending'}</span></div><details class="cv-evidence-details" open><summary>Every source mention</summary><ul>${mentions.map(mentionRow).join('')}</ul></details></article>`}
function creatorMatches(c){if(state.platform!=='all'&&c.platform!==state.platform)return false;if(state.creator!=='all'&&c.id!==state.creator)return false;if(state.query&&!norm([c.title,c.handle,c.role,c.status,c.coverage?.state,c.coverage?.notes].join(' ')).includes(norm(state.query)))return false;return true}
function videoMatches(v){if(!creatorAllowed(v.creatorId))return false;if(state.query)return true;return true}
function filteredCreators(){return creators.filter(creatorMatches).sort((a,b)=>Number(pinned.has(b.id))-Number(pinned.has(a.id))||Number(b.required)-Number(a.required)||String(a.title).localeCompare(String(b.title)))}
function filteredVideos(){return videos.filter(videoMatches).sort((a,b)=>String(b.publishedAt).localeCompare(String(a.publishedAt)))}
function renderRecommendations(){if(state.query.trim()){const rows=filteredProjects();return rows.length?`<div class="cv-merge-notice"><strong>Duplicate-free search</strong><span>${rows.length} canonical projects matched. Repeated creator/video mentions are merged below without losing their source evidence.</span></div><div class="cv-project-grid">${rows.map(mergedProjectCard).join('')}</div>`:`<div class="cv-empty"><strong>No sourced projects match.</strong><span>Broaden the creator or search filter. Nothing was deleted.</span></div>`}const rows=filteredVideos();return rows.length?rows.map(videoCard).join(''):`<div class="cv-empty"><strong>No sourced recommendations match.</strong><span>Broaden the creator filter. Nothing was deleted.</span></div>`}
function renderCreators(){const rows=filteredCreators();return rows.length?`<div class="cv-creator-grid">${rows.map(creatorCard).join('')}</div>`:`<div class="cv-empty"><strong>No creators match.</strong><span>Reset the filters to return to the full creator ledger.</span></div>`}
function setupMatches(p){if(!creatorAllowed(p.creatorId))return false;if(!state.query)return true;return norm([p.name,p.canonicalName,p.evidence,...entityLinks(p).flatMap(link=>[providerForUrl(link),link.url])].join(' ')).includes(norm(state.query))}
function renderSetup(){const rows=setupPacks.filter(setupMatches);return rows.length?`<div class="cv-setup-grid">${rows.map(p=>{const c=creatorById.get(p.creatorId)||{};return `<article class="cv-setup-card"><div class="cv-eyebrow">Used across ${p.sourceVideoIds?.length||0} indexed videos</div><h3>${esc(p.canonicalName||p.name)}</h3>${p.canonicalName&&p.canonicalName!==p.name?`<div class="cv-alias-line">Listed as ${esc(p.name)}</div>`:''}<p>${esc(p.evidence)}</p><div class="cv-mini-row"><span>${esc(c.title||p.creatorId)}</span><span>${esc(projectTypeLabel(p.projectType||'resourcepack'))}</span>${providerBadges(p)}</div><div class="cv-setup-actions">${providerActions(p,p.canonicalName||p.name)}</div></article>`}).join('')}</div>`:`<div class="cv-empty"><strong>No recurring setup packs match.</strong><span>These are separated from the creator's main video recommendations.</span></div>`}
function renderBody(){const body=$('creatorVaultBody');if(!body)return;body.innerHTML=state.view==='creators'?renderCreators():state.view==='setup'?renderSetup():renderRecommendations();document.querySelectorAll('[data-cv-view]').forEach(b=>b.classList.toggle('active',b.dataset.cvView===state.view));document.querySelectorAll('[data-cv-platform]').forEach(b=>b.classList.toggle('active',b.dataset.cvPlatform===state.platform));const creatorSelect=$('creatorVaultCreatorFilter');if(creatorSelect)creatorSelect.value=state.creator;const result=$('creatorVaultResultLabel');if(result){if(state.view==='recommendations'&&state.query.trim()){const rows=filteredProjects(),mentions=rows.reduce((n,p)=>n+scopedMentions(p).length,0);result.textContent=`${rows.length} projects · ${mentions} mentions`}else{const count=state.view==='creators'?filteredCreators().length:state.view==='setup'?setupPacks.filter(setupMatches).length:filteredVideos().reduce((n,v)=>n+(v.mods||[]).length,0);result.textContent=`${count} ${state.view==='recommendations'?'mentions':state.view==='creators'?'creators':'setup packs'}`}}}
function closeVault(){const modal=$('creatorVaultModal'),backdrop=$('creatorVaultBackdrop');if(modal)modal.hidden=true;if(backdrop)backdrop.hidden=true;document.body.classList.remove('creator-vault-open')}
function openVault(){const modal=$('creatorVaultModal'),backdrop=$('creatorVaultBackdrop');if(!modal||!backdrop)return;modal.hidden=false;backdrop.hidden=false;document.body.classList.add('creator-vault-open');renderBody();setTimeout(()=>$('creatorVaultSearch')?.focus(),0)}
function searchCatalog(term){closeVault();const input=$('searchInput');if(!input)return;input.value=term;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus()}
function copyText(text){if(navigator.clipboard?.writeText)return navigator.clipboard.writeText(text).catch(()=>fallbackCopy(text));fallbackCopy(text);return Promise.resolve()}
function fallbackCopy(text){const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();try{document.execCommand('copy')}catch{}area.remove()}
function buildShell(){const quick=document.querySelector('.quick-filters');if(quick&&!$('creatorVaultButton')){const button=document.createElement('button');button.id='creatorVaultButton';button.type='button';button.className='quick-chip creator-vault-chip';button.title=`${VAULT.stats?.recommendations||0} recommendation mentions merged into ${VAULT.stats?.uniqueProjects||projects.length} unique projects`;button.innerHTML=`Creators <span>${VAULT.stats?.uniqueProjects||projects.length}</span>`;button.addEventListener('click',openVault);quick.appendChild(button)}
const creatorOptions=creators.slice().sort((a,b)=>String(a.title).localeCompare(String(b.title))).map(c=>`<option value="${esc(c.id)}">${esc(c.title)} (${esc(platformLabel(c.platform))})</option>`).join('');const root=document.createElement('div');root.id='creator-vault-root';root.innerHTML=`<div id="creatorVaultBackdrop" class="cv-backdrop" hidden></div><section id="creatorVaultModal" class="creator-vault-modal" role="dialog" aria-modal="true" aria-labelledby="creatorVaultTitle" hidden><header class="cv-hero"><div><div class="cv-eyebrow">Enderloom creator intelligence</div><h2 id="creatorVaultTitle">Creator Vault</h2><p>Browse creator recommendations with the source evidence intact. Search is duplicate-free: repeated mentions and aliases merge into one canonical project card, and every independently verified provider home appears as its own direct button.</p></div><button type="button" class="cv-close" data-cv-close aria-label="Close Creator Vault">Close</button></header><section class="cv-stats"><div><span>Tracked creators</span><strong>${Number(VAULT.stats?.creators||creators.length)}</strong></div><div><span>Recommendation mentions</span><strong>${Number(VAULT.stats?.recommendations||0)}</strong></div><div><span>Unique projects</span><strong>${Number(VAULT.stats?.uniqueProjects||projects.length)}</strong></div><div><span>Projects with direct links</span><strong>${Number(VAULT.stats?.verifiedProjects||0)}</strong></div><div><span>Multi-provider projects</span><strong>${Number(VAULT.stats?.multiProviderProjects||0)}</strong></div><div><span>Provider destinations</span><strong>${Number(VAULT.stats?.providerDestinations||0)}</strong></div></section><div class="cv-toolbar"><div class="cv-tabs"><button type="button" class="active" data-cv-view="recommendations">Recommendations</button><button type="button" data-cv-view="creators">Creators</button><button type="button" data-cv-view="setup">Setup packs</button></div><div class="cv-platform-tabs"><button type="button" class="active" data-cv-platform="all">All</button><button type="button" data-cv-platform="youtube">YouTube</button><button type="button" data-cv-platform="tiktok">TikTok</button></div><div class="cv-search-row"><input id="creatorVaultSearch" type="search" autocomplete="off" placeholder="Search merged projects, aliases, creators, loaders, providers..."><select id="creatorVaultCreatorFilter"><option value="all">All creators</option>${creatorOptions}</select><span id="creatorVaultResultLabel"></span></div></div><div id="creatorVaultBody" class="cv-body"></div><footer class="cv-footer"><span>Strategy: ${esc(VAULT.strategy||'full-history-first/incremental-after')}</span><span>${VAULT.diagnostics?.length?`${VAULT.diagnostics.length} loader note(s)`:'Creator data loaded cleanly'}</span></footer></section>`;document.body.appendChild(root);
$('creatorVaultBackdrop').addEventListener('click',closeVault);root.addEventListener('click',event=>{const close=event.target.closest('[data-cv-close]');if(close){closeVault();return}const view=event.target.closest('[data-cv-view]');if(view){state.view=view.dataset.cvView;renderBody();return}const platform=event.target.closest('[data-cv-platform]');if(platform){state.platform=platform.dataset.cvPlatform;renderBody();return}const pin=event.target.closest('[data-pin-creator]');if(pin){const id=pin.dataset.pinCreator;pinned.has(id)?pinned.delete(id):pinned.add(id);persistPins();renderBody();return}const creatorCardEl=event.target.closest('[data-creator-id]');if(creatorCardEl&&!event.target.closest('a,button')){state.creator=creatorCardEl.dataset.creatorId;state.view='recommendations';renderBody();return}const search=event.target.closest('[data-catalog-search]');if(search){searchCatalog(search.dataset.catalogSearch);return}const copy=event.target.closest('[data-copy-video]');if(copy){const video=videos.find(v=>v.id===copy.dataset.copyVideo);if(video){copyText((video.mods||[]).map(m=>m.canonicalName||m.name).filter((name,index,rows)=>rows.indexOf(name)===index).join('\n'));copy.textContent='Copied';setTimeout(()=>copy.textContent='Copy mod names',1200)}}});$('creatorVaultSearch').addEventListener('input',event=>{state.query=event.target.value||'';renderBody()});$('creatorVaultCreatorFilter').addEventListener('change',event=>{state.creator=event.target.value||'all';renderBody()});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('creatorVaultModal')?.hidden)closeVault()});renderBody()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',buildShell,{once:true});else buildShell();
})();
