'use strict';
const fs=require('fs');const os=require('os');const path=require('path');const assert=require('assert');
const {CatalogStore,inferGoogle}=require('../src/catalog-store');
const {parseSourceBuffer,ACCEPTED_EXTENSIONS}=require('../src/ingest');
const root=path.resolve(__dirname,'..'),fixtures=path.join(__dirname,'fixtures');
const checks=[];
function check(name,fn){try{fn();checks.push({name,ok:true})}catch(e){checks.push({name,ok:false,error:e.message});throw e}}
function fixture(name){return fs.readFileSync(path.join(fixtures,name))}
async function waitFor(predicate,{timeout=7000,interval=100}={}){const deadline=Date.now()+timeout;while(Date.now()<deadline){if(predicate())return true;await new Promise(r=>setTimeout(r,interval))}return !!predicate()}
(async()=>{
 const mv=JSON.parse(fs.readFileSync(path.join(root,'catalog/catalogs/mob-variety.json'),'utf8'));
 const mg=JSON.parse(fs.readFileSync(path.join(root,'catalog/catalogs/mob-girl.json'),'utf8'));
 check('Mob Variety exact count',()=>assert.equal(mv.items.length,293));
 check('Mob Variety collections',()=>assert.equal(mv.build.collections,19));
 check('Mob Variety ships no static embedded media',()=>{assert.equal(Object.keys(mv.assets).length,0);assert(mv.items.every(x=>!x.iconAsset&&!x.authorAsset&&!x.galleryAsset))});
 check('Mob Variety live media source coverage',()=>assert(mv.items.every(x=>/^https?:\/\//.test(x.primaryUrl||''))));
 check('Mob Girl exact count',()=>assert.equal(mg.items.length,312));
 check('Mob Girl ranks 1..312',()=>{assert.equal(mg.items[0].rank,1);assert.equal(mg.items.at(-1).rank,312)});
 check('Mob Girl scores absent',()=>assert(mg.items.every(x=>x.overallScore===null||x.overallScore===undefined||x.overallScore==='')));
 check('Unique stable IDs',()=>{for(const x of [mv,mg])assert.equal(new Set(x.items.map(i=>i.id)).size,x.items.length)});
 check('Exact HTTP primary links',()=>{for(const x of [mv,mg])assert(x.items.every(i=>/^https?:\/\//.test(i.primaryUrl||'')))});
 check('Google URL inference',()=>{const x=inferGoogle('https://docs.google.com/spreadsheets/d/abc_DEF-123/edit');assert.equal(x.format,'xlsx');assert.equal(x.id,'abc_DEF-123')});
 check('Declared ingest extensions',()=>{for(const ext of ['.xlsx','.xlsm','.csv','.tsv','.json','.docx','.pdf','.md','.markdown','.txt','.html','.htm','.zip'])assert(ACCEPTED_EXTENSIONS.has(ext),ext)});
 const tinyXlsx=parseSourceBuffer(fixture('tiny-catalog.xlsx'),{filePath:'tiny-catalog.xlsx'});
 check('XLSX ingest fixture',()=>{assert.equal(tinyXlsx.items.length,2);assert.equal(tinyXlsx.items[0].rank,1);assert.equal(tinyXlsx.items[0].overallScore,9.5);assert.equal(tinyXlsx.items[1].primaryUrl,'https://example.com/beta')});
 const tinyDoc=parseSourceBuffer(fixture('tiny-guide.docx'),{filePath:'tiny-guide.docx'});
 check('DOCX narrative ingest fixture',()=>{assert.equal(tinyDoc.documents.length,1);assert(tinyDoc.documents[0].text.includes('Narrative context'))});
 const tinyPdf=parseSourceBuffer(fixture('tiny-guide.pdf'),{filePath:'tiny-guide.pdf'});
 check('PDF fixed narrative ingest fixture',()=>{assert.equal(tinyPdf.meta.pageCount,1);assert.equal(tinyPdf.meta.textExtractionMode,'lightweight-best-effort');assert(tinyPdf.documents[0].text.includes('Fixture PDF narrative'))});
 const tinyBundle=parseSourceBuffer(fixture('tiny-bundle.zip'),{filePath:'tiny-bundle.zip'});
 check('ZIP catalog bundle ingest fixture',()=>assert.equal(tinyBundle.items[0].primaryUrl,'https://example.com/bundle'));
 check('CSV ingest fixture',()=>assert.equal(parseSourceBuffer(Buffer.from('Name,Primary URL\nCSV Fixture,https://example.com/csv\n'),{filePath:'x.csv'}).items.length,1));
 check('TSV ingest fixture',()=>assert.equal(parseSourceBuffer(Buffer.from('Name\tPrimary URL\nTSV Fixture\thttps://example.com/tsv\n'),{filePath:'x.tsv'}).items.length,1));
 check('JSON ingest fixture',()=>assert.equal(parseSourceBuffer(Buffer.from('{"items":[{"name":"JSON Fixture","primaryUrl":"https://example.com/json"}]}'),{filePath:'x.json'}).items.length,1));
 check('Markdown narrative ingest fixture',()=>assert(parseSourceBuffer(Buffer.from('# Guide\nNarrative markdown'),{filePath:'x.md'}).documents[0].text.includes('Narrative markdown')));
 const fake={cookies:{get:async()=>[{name:'SID',value:'fixture'}]}};
 const fakeGoogleRequest=async(_url,opts={})=>{const dynamic=await opts.headersForUrl?.('https://docs.google.com/spreadsheets/d/fixture_sheet/export?format=xlsx');assert(/SID=fixture/.test(dynamic?.Cookie||''));return{status:200,headers:{'content-type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','etag':'"fixture-v1"'},buffer:fixture('tiny-catalog.xlsx')}};
 const legacyTmp=fs.mkdtempSync(path.join(os.tmpdir(),'catalog-companion-legacy-')),legacyDir=path.join(legacyTmp,'catalog-workspace'),legacyData=path.join(legacyDir,'data');fs.mkdirSync(legacyData,{recursive:true});
 const legacyCsv=path.join(legacyTmp,'legacy.csv');fs.writeFileSync(legacyCsv,'Name,Primary URL\nLegacy Project,https://example.com/legacy\n');
 const legacyCustom=path.join(legacyData,'legacy-custom.json');fs.writeFileSync(legacyCustom,JSON.stringify({id:'legacy-custom',title:'Legacy Custom',items:[{id:'legacy-1',name:'Legacy Project',primaryUrl:'https://example.com/legacy'}],assets:{},documents:[]}));
 fs.writeFileSync(path.join(legacyDir,'registry.json'),JSON.stringify([{id:'mob-girls',title:'Mob Girls',sources:[{id:'mg-local-extra',localPath:legacyCsv,role:'structured',export:'csv',name:'Legacy local source'}]},{id:'legacy-custom',title:'Legacy Custom',dataFile:legacyCustom,sources:[{id:'legacy-source',localPath:legacyCsv,role:'structured',export:'csv',name:'Legacy CSV'}]}]));
 fs.writeFileSync(path.join(legacyTmp,'session.json'),JSON.stringify({currentCatalogId:'mob-girls'}));
 const legacyStore=new CatalogStore({rootDir:root,userDataDir:legacyTmp,liveSession:fake,googleRequest:fakeGoogleRequest,testMode:true});await legacyStore.init();
 check('1.2 workspace migration marker',()=>assert(legacyStore.registry.migrations.includes('catalog-workspace-v1.2')));
 check('1.2 active Mob Girls maps to Mob Girl',()=>assert.equal(legacyStore.registry.activeCatalogId,'mob-girl'));
 check('1.2 custom catalog migrates',()=>{assert(legacyStore.entry('legacy-custom'));assert.equal(legacyStore.loadSnapshot('legacy-custom').items.length,1);assert.equal(legacyStore.entry('legacy-custom').sources[0].location,'local')});
 check('1.2 builtin extra source migrates',()=>assert(legacyStore.entry('mob-girl').sources.some(x=>x.id==='mg-local-extra'&&x.path===legacyCsv)));legacyStore.dispose();
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'mob-companion-qa-'));
 const store=new CatalogStore({rootDir:root,userDataDir:tmp,liveSession:fake,googleRequest:fakeGoogleRequest,testMode:true});await store.init();
 check('Registry seeds two catalogs',()=>assert(store.summary().catalogs.some(x=>x.id==='mob-variety')&&store.summary().catalogs.some(x=>x.id==='mob-girl')));
 await store.activate('mob-girl');check('Hot switch Mob Girl',()=>assert.equal(store.loadSnapshot().items.length,312));
 const csv=path.join(tmp,'hot.csv');fs.writeFileSync(csv,'Name,Category,Primary URL\nAlpha,Test,https://example.com/alpha\nBeta,Test,https://example.com/beta\n');
 await store.addLocalFiles([csv],{mode:'smart'});const hotId=store.summary().activeCatalogId;check('Hot-drop creates catalog',()=>assert.equal(store.loadSnapshot(hotId).items.length,2));
 const hotMtimeBefore=fs.statSync(csv).mtimeMs;fs.writeFileSync(csv,'Name,Category,Primary URL\nAlpha,Test,https://example.com/alpha\nBeta,Test,https://example.com/beta\nGamma,Test,https://example.com/gamma\n');const bumped=new Date(hotMtimeBefore+5000);fs.utimesSync(csv,bumped,bumped);
 await waitFor(()=>store.loadSnapshot(hotId).items.length===3);check('Local watcher hot refreshes',()=>assert.equal(store.loadSnapshot(hotId).items.length,3));
 const groupXlsx=path.join(tmp,'group.xlsx'),groupDoc=path.join(tmp,'group.docx'),groupPdf=path.join(tmp,'group.pdf');fs.copyFileSync(path.join(fixtures,'tiny-catalog.xlsx'),groupXlsx);fs.copyFileSync(path.join(fixtures,'tiny-guide.docx'),groupDoc);fs.copyFileSync(path.join(fixtures,'tiny-guide.pdf'),groupPdf);
 await store.addLocalFiles([groupXlsx,groupDoc,groupPdf],{mode:'new'});const groupedId=store.summary().activeCatalogId,grouped=store.loadSnapshot(groupedId);check('Grouped hot-drop is one catalog',()=>{assert.equal(grouped.items.length,2);assert.equal(store.entry(groupedId).sources.length,3);assert.equal(grouped.documents.length,2)});
 await store.addGoogleSource('https://docs.google.com/spreadsheets/d/fixture_sheet/edit',{catalogId:groupedId,role:'primary'});check('Google cookie-bridged Node transport refreshes structured source',()=>assert.equal(store.loadSnapshot(groupedId).items.length,2));
 const gsrc=store.entry(groupedId).sources.find(x=>x.location==='google');gsrc.etag='';const repeat=await store.refreshSource(groupedId,gsrc.id,{reason:'qa-repeat'});check('Unchanged Google source is zero-loss no-op',()=>assert.equal(repeat.changed,false));
 const runtime=store.runtimePath(groupedId);check('Runtime HTML generated',()=>{const h=fs.readFileSync(runtime,'utf8');assert(h.includes('Fixture Alpha'));assert(!h.includes('__BUILD_JSON__'));assert(!h.includes('__DATA_JSON__'));assert(h.includes('data-live-media-role'));assert(!h.includes('data:image/'))});
 check('Mob Girl PDF retained as fixed source',()=>{const pdf=mg.sources.find(x=>x.role==='fixed'&&x.format==='pdf');assert(pdf);assert(mg.documents.some(d=>d.sourceId===pdf.id))});
 const allSummary=await store.refreshAllCatalogs();check('Refresh all catalogs command path',()=>assert.equal(allSummary.catalogs.length,store.registry.catalogs.length));
 store.dispose();
 console.log(JSON.stringify({passed:checks.every(x=>x.ok),checks},null,2));
})().catch(e=>{console.error(JSON.stringify({passed:false,checks,error:e.stack},null,2));process.exit(1)});
