'use strict';
const assert=require('assert/strict');
const fs=require('fs');
const os=require('os');
const path=require('path');
const {spawnSync}=require('child_process');
const crypto=require('crypto');
const root=path.resolve(__dirname,'..');
const binary=path.join(root,'native/target/debug',process.platform==='win32'?'enderloom.exe':'enderloom');
const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'enderloom-cli-qa-'));
const data=path.join(temporary,'data');
let checks=0;
function call(args,input={},exit=0){
  const result=spawnSync(binary,['--data-dir',data,...args],{input:JSON.stringify(input),encoding:'utf8',timeout:30000,windowsHide:true});
  assert.ifError(result.error);
  assert.equal(result.status,exit,`${args.join(' ')}: ${result.stderr}\n${result.stdout}`);
  assert(!/\u001b\[/.test(result.stdout),'ANSI escape in machine output');
  const rows=result.stdout.trim().split(/\r?\n/);
  const envelope=args.includes('--jsonl')?rows.map(s=>JSON.parse(s)).at(-1):JSON.parse(result.stdout);
  assert.equal(envelope.schema_version,1);
  assert.equal(typeof envelope.trace_id,'string');
  assert.equal(envelope.ok,exit===0);
  checks++;
  return envelope;
}
try{
  const capabilities=call(['capabilities','--json']).result;
  assert(capabilities.length>200);
  assert(capabilities.some(c=>c.id==='scan_instance_workbench'));
  assert(!fs.existsSync(data),'Capability discovery should not create/open user data');
  assert(call(['--help','--json']).result.text.includes('capabilities'));
  assert(call(['--version','--jsonl']).result.text.includes('enderloom'));
  call(['instance','list','--plan','--json'],{},2);
  assert(!fs.existsSync(data),'Invalid plans must not open user data');
  assert.deepEqual(call(['instance','list','--json']).result,[]);
  assert.deepEqual(call(['--list','--json']).result,[]);
  call(['not-a-command','--json'],{},2);
  call(['instance','list','--nonsense','--json'],{},2);
  call(['instance','show','--json'],{},2);
  call(['--launch','one','--launch','two','--json'],{},2);
  call(['--launch','missing','--json'],{},3);
  call(['launch','missing','--detach','--wait','--json'],{},2);
  const create=(name)=>call(['operation','run','create_instance','--json'],{name,versionId:'1.20.1',loader:null,loaderVersion:null}).result;
  const one=create('CLI fixture'),two=create('Duplicate name'),three=create('Duplicate name');
  assert.notEqual(two.id,three.id);
  assert.equal(call(['instance','show','CLI fixture','--json']).result.id,one.id);
  assert.equal(call(['instance','show',one.id,'--json','--trace-id','qa-stable-id']).trace_id,'qa-stable-id');
  const legacy=spawnSync(binary,['--data-dir',data,'--list'],{encoding:'utf8',windowsHide:true});
  assert.equal(legacy.status,0);assert(legacy.stdout.includes('CLI fixture'));assert(legacy.stdout.includes(one.id.replace(/-/g,'').slice(0,8)));
  const output=path.join(temporary,'result.json');
  const written=call(['instance','show',one.id,'--json','--output',output]);
  assert.deepEqual(JSON.parse(fs.readFileSync(output,'utf8')),written);
  assert.equal(call(['instance','show',one.id.replace(/-/g,'').slice(0,8),'--json']).result.id,one.id);
  call(['instance','show','Duplicate name','--json'],{},3);
  call(['instance','show','no match','--json'],{},3);
  assert.equal(call(['--list','--launch','ignored','--json']).result.length,3);
  fs.mkdirSync(path.join(one.dir,'logs'),{recursive:true});
  fs.writeFileSync(path.join(one.dir,'logs/latest.log'),'[12:00:00] [main/INFO]: CLI proof\nAuthorization: Bearer very-secret-token\n');
  assert(call(['logs','list',one.id,'--json']).result.length>0);
  const log=call(['logs','show',one.id,'latest.log','--json']);
  assert(!JSON.stringify(log).includes('very-secret-token'),'Log secret not redacted');
  assert.deepEqual(call(['process','list','--json']).result,[]);
  assert.equal(call(['instance','list','--jsonl']).result.length,3);
  call(['operation','run','delete_instance','--json'],{instanceId:one.id},3);
  assert(fs.existsSync(one.dir),'Missing --yes must not delete anything');
  const fromFile=path.join(temporary,'args.json');
  fs.writeFileSync(fromFile,JSON.stringify({instanceId:one.id}));
  call(['operation','run','delete_instance','--input',fromFile,'--yes','--json']);
  assert(!fs.existsSync(one.dir));
  const schema=call(['schema','--json']);
  assert.equal(schema.result.result_schema,1);
  const help=spawnSync(binary,['--help'],{encoding:'utf8',windowsHide:true});
  assert.equal(help.status,0);assert(help.stdout.includes('capabilities'));
  console.log(JSON.stringify({passed:true,checks,binary,binarySha256:crypto.createHash('sha256').update(fs.readFileSync(binary)).digest('hex'),sharedDomainFixture:true,jsonStdoutClean:true,selectorsVerified:true},null,2));
}finally{
  const resolved=path.resolve(temporary);
  if(resolved.startsWith(path.resolve(os.tmpdir())+path.sep)&&path.basename(resolved).startsWith('enderloom-cli-qa-'))fs.rmSync(resolved,{recursive:true,force:true});
}
