'use strict';
const assert=require('assert/strict'),path=require('path'),fs=require('fs');const{_electron:electron}=require('playwright');const{fixture}=require('./spark-evidence-qa');
const root=path.resolve(__dirname,'..');let app;
(async()=>{
  app=await electron.launch({executablePath:path.join(root,'node_modules/electron/dist/electron.exe'),args:[path.join(root,'scripts/fixtures/creative-ui-host.cjs')]});const page=await app.firstWindow();page.setDefaultTimeout(12000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.getByRole('button',{name:'Open Evergreen · creative workshop',exact:true}).waitFor();await page.getByRole('button',{name:'Performance',exact:true}).first().click();await page.getByRole('button',{name:'Spark & logs',exact:true}).click();
  await page.locator('input[type="file"]').setInputFiles({name:'reference.sparkprofile',mimeType:'application/octet-stream',buffer:fixture()});await page.getByRole('heading',{name:'Mod share · exclusive samples'}).waitFor();
  await page.getByText('Evidence & source',{exact:true}).click();await page.getByText('sampled',{exact:true}).waitFor();await page.getByRole('button',{name:'Verify source',exact:true}).click();await page.getByText('Source: verified · Analysis: verified',{exact:true}).waitFor();
  await page.locator('input[type="file"]').setInputFiles({name:'latest.log',mimeType:'text/plain',buffer:Buffer.from("[Server thread/WARN]: Can't keep up! Running 2100ms behind\n--accessToken fixture-secret-never-persist")});await page.getByText('Server falling behind · 1',{exact:true}).waitFor();await page.getByText('Evidence & source',{exact:true}).click();await page.getByText('inferred',{exact:true}).waitFor();await page.getByRole('button',{name:'Verify source',exact:true}).click();await page.getByText('Source: verified · Analysis: verified',{exact:true}).waitFor();
  const records=await app.evaluate(async()=>{const{service,fixtures}=global.creativeQa;return service.request('get_evidence_artifacts',{targetKind:'instance',targetId:fixtures.instance.id});});const spark=records.find(r=>r.kind==='spark_profile'),log=records.find(r=>r.kind==='log_analysis');assert(!fs.readFileSync(log.raw.path,'utf8').includes('fixture-secret-never-persist'));
  await page.getByLabel('Related evidence',{exact:true}).selectOption(spark.id);await page.getByLabel('Evidence relationship',{exact:true}).selectOption('comparison');await page.getByLabel('Evidence relationship reason',{exact:true}).fill('Compare the reported stall with the sampled thread before attributing cause.');await page.getByRole('button',{name:'Link evidence',exact:true}).click();await page.getByText('Compare the reported stall with the sampled thread before attributing cause.',{exact:true}).waitFor();
  fs.writeFileSync(log.raw.path,'altered fixture source');await page.getByRole('button',{name:'Verify source',exact:true}).click();await page.getByText('Source: changed · Analysis: verified',{exact:true}).waitFor();
  await page.screenshot({path:path.join(root,'output/playwright/evidence-integrity.png')});
  await page.reload();await page.getByRole('button',{name:'Performance',exact:true}).first().click();await page.getByRole('button',{name:'Spark & logs',exact:true}).click();await page.getByText('Server falling behind · 1',{exact:true}).waitFor();await page.getByText('Evidence & source',{exact:true}).click();await page.getByText('Compare the reported stall with the sampled thread before attributing cause.',{exact:true}).waitFor();
  assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,profileSourceVerified:true,redactedLogVerified:true,relationshipsPersist:true,changedSourceWarning:true,rendererErrors:errors},null,2));
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>app?.close());
