'use strict';
const assert = require('assert/strict'), fs = require('fs'), path = require('path');
const { _electron: electron } = require('playwright');
const root = path.resolve(__dirname, '..'), output = path.join(root, 'output/playwright');
let app;
(async () => {
  app = await electron.launch({ executablePath: path.join(root, 'node_modules/electron/dist/electron.exe'), args: [path.join(root, 'scripts/fixtures/creative-ui-host.cjs')] });
  const page = await app.firstWindow(); page.setDefaultTimeout(15000);
  const errors = []; page.on('pageerror', e=>errors.push(e.message));
  const home = () => page.getByRole('button', {name:'Home', exact:true}).first().click();
  const card = page.locator('.home-instance').filter({hasText:'Evergreen · creative workshop'});
  await card.waitFor();
  const title = await card.locator('strong').boundingBox();
  await page.mouse.click(title.x+title.width/2, title.y+title.height/2);
  await page.getByRole('button',{name:'Mods',exact:true}).waitFor();
  assert.equal(await page.locator('.home-library').count(), 0, 'Clicking the card title opens its instance');
  await home();
  await page.getByRole('button',{name:'Open Evergreen · creative workshop',exact:true}).press('Enter');
  await page.getByRole('button',{name:'Mods',exact:true}).waitFor();
  await home();
  await page.getByRole('button',{name:'Play Evergreen · creative workshop',exact:true}).click();
  await page.getByText('Sign in to Minecraft to play.',{exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Mods',exact:true}).count(), 0, 'Play does not bubble into instance navigation');
  await home();
  await page.getByTestId('home-view-trigger').click(); await page.getByRole('button',{name:'List',exact:true}).click();
  await page.locator('.home-instance-list').waitFor();
  await page.keyboard.press('Escape');
  const area = await card.boundingBox();
  await page.mouse.click(area.x+area.width/2,area.y+area.height/2);
  await page.getByRole('button',{name:'Mods',exact:true}).waitFor();
  await home();
  await page.getByRole('button',{name:'New instance',exact:true}).click();
  await page.getByRole('button',{name:/Start from nothing/}).click();
  await page.getByRole('button',{name:'26.3 release',exact:true}).waitFor({timeout:45000});
  await page.getByRole('button',{name:'26.3 release',exact:true}).click();
  await page.getByRole('button',{name:'Fabric',exact:true}).click();
  await page.getByText('0.19.5',{exact:true}).waitFor({timeout:30000});
  await page.getByRole('button',{name:'Refresh game and loader versions'}).click();
  await page.getByRole('button',{name:'Refresh game and loader versions'}).waitFor({state:'visible'});
  await page.getByText('0.19.5',{exact:true}).waitFor({timeout:30000});
  fs.mkdirSync(output,{recursive:true}); await page.screenshot({path:path.join(output,'minecraft-26.3-create.png')});
  await page.getByRole('button',{name:'Cancel',exact:true}).click(); await home();
  await page.locator('.home-library').waitFor();
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1050,800));
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth), 'Home fits a smaller window');
  await page.waitForTimeout(350);
  await page.screenshot({path:path.join(output,'home-clickable-cards.png')});
  assert.deepEqual(errors,[]);
  console.log('PASS real Electron Home card title, keyboard and list navigation; independent Play; live 26.3/Fabric version refresh; compact viewport; zero renderer errors.');
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{await app?.close();});
