'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const main=fs.readFileSync(path.join(root,'main.js'),'utf8');
const shell=fs.readFileSync(path.join(root,'shell.js'),'utf8');
const css=fs.readFileSync(path.join(root,'shell.css'),'utf8');
const splitter=fs.readFileSync(path.join(root,'splitter.js'),'utf8');
assert(fs.existsSync(path.join(root,'splitter.html'))&&fs.existsSync(path.join(root,'splitter.css')),'native splitter renderer missing');
assert(main.includes('let splitterView = null'),'native splitter view missing');
assert(main.includes('function setupSplitterOverlay()'),'native splitter setup missing');
assert(main.includes("splitterView.webContents.loadFile(path.join(ROOT,'splitter.html'))"),'native splitter does not load dedicated renderer');
assert(main.includes('function layoutSplitterOverlay()'),'splitter layout missing');
assert(main.includes('width:DIVIDER_W'),'splitter native hit lane is not DIVIDER_W');
assert(main.includes('splitAvailableWidth: splitGeometry().available'),'splitter does not publish stable drag geometry');
assert(main.includes('if (splitterView && splitMode'),'protected z-order does not include splitter');
assert(shell.includes("classList.add('native-splitter-managed')"),'legacy shell splitter is not suppressed');
assert(css.includes('html.native-splitter-managed .split-divider{display:none!important}'),'legacy splitter can still steal/duplicate visuals');
assert(splitter.includes('e.screenX')&&splitter.includes('startScreenX'),'drag math is not stable across moving native view bounds');
assert(splitter.includes('setPointerCapture'),'splitter does not capture drag pointer');
assert(splitter.includes("cmd('split-reset')")&&splitter.includes("cmd('split-swap')"),'splitter QoL actions missing');
assert(splitter.includes("e.key==='ArrowLeft'")&&splitter.includes("e.key==='End'"),'splitter keyboard resize missing');
console.log(JSON.stringify({passed:true,nativeSplitter:true,fullHeightHitLane:true,stableScreenCoordinateDrag:true,keyboard:true,swap:true,reset:true},null,2));
