'use strict';
const assert = require('assert/strict'), path = require('path'), fs = require('fs');
const { _electron: electron } = require('playwright');
let app;
(async () => {
  const root = path.resolve(__dirname, '..'), out = path.join(root, 'output/trailers'); fs.mkdirSync(out, { recursive: true });
  app = await electron.launch({ executablePath: path.join(root, 'node_modules/electron/dist/electron.exe'), args: [path.join(root, 'scripts/fixtures/trailer-ui-host.cjs')] });
  const page = await app.firstWindow(), errors = []; page.on('pageerror', e => errors.push(e.message));
  const first = page.locator('.project-card').first(), second = page.locator('.project-card').nth(1);
  await page.getByRole('button', { name: 'Trailer previews', exact: true }).waitFor();
  await first.scrollIntoViewIfNeeded(); await first.hover(); await page.waitForTimeout(1100);
  assert.equal(await page.locator('.trailer-player').count(), 0, 'Autoplay starts disabled');
  await page.getByRole('button', { name: 'Trailer previews', exact: true }).click();
  await page.getByLabel('Enable automatic trailer previews', { exact: true }).check();
  await page.getByLabel('Preview on Catalog hover or keyboard focus', { exact: true }).check();
  await page.getByRole('button', { name: 'Done', exact: true }).click();
  await first.scrollIntoViewIfNeeded(); await first.hover(); await page.waitForTimeout(200); await page.mouse.move(2,2); await page.waitForTimeout(1000);
  assert.equal(await page.locator('.trailer-player').count(), 0, 'Transient hover creates no player');
  await first.hover(); await page.locator('.trailer-player').waitFor({ timeout: 45000 });
  assert.equal(await page.locator('.trailer-player').count(), 1);
  assert.match(await page.locator('.trailer-player').getAttribute('src'), /mute=1/);
  const frame = page.frames().find(f => f.url().includes('youtube.com/embed/'));
  await page.waitForTimeout(7000);
  const media = await frame.evaluate(() => { const v = document.querySelector('video'); return { title: document.title, time: v?.currentTime, paused: v?.paused, muted: v?.muted, error: document.querySelector('.ytp-error-content-wrap')?.textContent }; });
  console.log('LIVE YOUTUBE', JSON.stringify(media));
  await first.getByRole('button', { name: 'Preview trailer for Create', exact: true }).click();
  await page.waitForTimeout(600); assert.equal(await frame.evaluate(() => document.querySelector('video')?.paused), true, 'Pause controls the actual provider player');
  await first.getByRole('button', { name: 'Preview trailer for Create', exact: true }).click();
  await page.waitForTimeout(600); assert.equal(await frame.evaluate(() => document.querySelector('video')?.paused), false, 'Resume controls the actual provider player');
  await page.screenshot({ path: path.join(out, 'catalog-live-trailer.png') });
  await page.mouse.move(2,2); await page.waitForTimeout(300); assert.equal(await page.locator('.trailer-player').count(), 0, 'Hover loss disposes iframe');
  await second.scrollIntoViewIfNeeded(); await second.hover(); await page.locator('.trailer-player').waitFor({ timeout: 45000 });
  assert.match(await page.locator('.trailer-player').getAttribute('src'), /jKu3fAZSaPw/);
  await page.mouse.wheel(0, 300); await page.waitForTimeout(300); assert.equal(await page.locator('.trailer-player').count(), 0, 'Scroll stops playback');
  await page.emulateMedia({ reducedMotion: 'reduce' }); await first.scrollIntoViewIfNeeded(); await first.hover(); await page.waitForTimeout(1200); assert.equal(await page.locator('.trailer-player').count(), 0, 'Reduced motion prevents autoplay');
  await first.getByRole('button', { name: 'Why this trailer?', exact: true }).click();
  await page.getByText('This is Create. (2022)', { exact: true }).waitFor();
  await page.screenshot({ path: path.join(out, 'why-this-trailer.png') });
  await page.getByLabel('Correct trailer URL').fill('https://www.youtube.com/watch?v=jKu3fAZSaPw');
  await page.getByRole('button', { name: 'Use my trailer', exact: true }).click();
  await page.getByText(/does not identify this exact mod/).waitFor();
  await page.getByRole('button', { name: 'Gallery only for this mod', exact: true }).click();
  await page.emulateMedia({ reducedMotion: 'no-preference' }); await first.hover(); await page.waitForTimeout(1500); assert.equal(await page.locator('.trailer-player').count(), 0, 'Per-project gallery-only selection is respected');
  await second.getByRole('button', { name: 'Full details', exact: true }).click();
  await page.locator('#projectModal .trailer-player').waitFor({ timeout: 45000 });
  assert.equal(await page.locator('.trailer-player').count(), 1, 'Detail hero owns the only player');
  await page.keyboard.press('Escape'); await page.waitForTimeout(300); assert.equal(await page.locator('.trailer-player').count(), 0, 'Closing detail disposes player');
  await page.mouse.move(2,2); await second.scrollIntoViewIfNeeded(); await page.waitForTimeout(500); await second.locator('.card-title a').focus(); await page.locator('.trailer-player').waitFor({ timeout: 10000 });
  await page.getByRole('button', { name: 'Trailer previews', exact: true }).focus(); await page.waitForTimeout(250); assert.equal(await page.locator('.trailer-player').count(), 0, 'Keyboard focus loss disposes player');
  await page.getByRole('button', { name: 'Trailer previews', exact: true }).click();
  await page.getByLabel('Save data · manual playback only', { exact: true }).check(); await page.getByRole('button', { name: 'Done', exact: true }).click();
  await second.hover(); await page.waitForTimeout(1300); assert.equal(await page.locator('.trailer-player').count(), 0, 'Data saver disables autoplay');
  await second.getByRole('button', { name: 'Preview trailer for The Aether', exact: true }).click(); await page.locator('.trailer-player').waitFor();
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].emit('blur')); await page.waitForTimeout(250); assert.equal(await page.locator('.trailer-player').count(), 0, 'App background releases player');
  await second.getByRole('button', { name: 'Preview trailer for The Aether', exact: true }).click(); await page.locator('.trailer-player').waitFor();
  await page.getByRole('button', { name: 'Table view', exact: true }).click(); await page.waitForTimeout(200); assert.equal(await page.locator('.trailer-player').count(), 0, 'Virtualized/replaced cards leave no iframe');
  await page.getByRole('button', { name: 'Card view', exact: true }).click();
  await page.route('https://www.youtube.com/embed/*', route => route.fulfill({ contentType: 'text/html', body: '<script>parent.postMessage(JSON.stringify({event:"onError",info:150}),"*")</script>' }));
  await second.getByRole('button', { name: 'Preview trailer for The Aether', exact: true }).click(); await page.getByText('Provider restricted this video · open its source or choose another trailer', { exact: true }).waitFor();
  assert.equal(await page.locator('.trailer-player').count(), 0, 'Login/embed restriction preserves gallery without bypass');
  assert.deepEqual(errors, []); fs.writeFileSync(path.join(out, 'runtime.json'), JSON.stringify({ media, errors, assertions: 'hover, muted, cancellation, scroll, reduced motion, provenance, correction, gallery-only, detail, navigation' }, null, 2));
  assert(media.time > 0 && media.paused === false && media.muted === true, 'Real YouTube video must play muted inside Electron');
  console.log('PASS real Electron trailer runtime');
})().catch(async e => { console.error(e); if (app) { const p = await app.firstWindow(); console.error(await p.evaluate(() => ({ focus: document.activeElement?.outerHTML, hidden: document.hidden, cards: [...document.querySelectorAll('.trailer-slot')].map(el => ({ rect: el.getBoundingClientRect().toJSON(), text: el.nextElementSibling?.textContent })) }))); await p.screenshot({ path: path.resolve(__dirname, '../output/trailers/failure.png') }); } process.exitCode = 1; }).finally(async () => { if (app) await app.close(); });
